application: connexus
version: 2
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  expiration: '1d'
- url: /js
  static_dir: js
- url: /.*
  script: main.app
- url: /login
  script: main.login



# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
